---
- hosts: all
  user: vagrant
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest
  roles:
    - epel
    - git
    - fish
    - ssh_key
    - docker
    - ansible
